services:
  caddy:
    build: .
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Provided via .env file below (do NOT hardcode here)
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data:
  caddy_config:
